# Generated by Django 4.2.7 on 2026-02-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0004_imagegeneration_brand_template_and_more'),
        ('posts', '0003_postcaption_post_angle_post_approved_at_post_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcaption',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='AI-suggested image prompt for this caption', null=True),
        ),
        migrations.AddField(
            model_name='scheduledpostplatform',
            name='asset_variant',
            field=models.ForeignKey(blank=True, help_text='Platform-specific resized creative asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_image.assetplatformvariant'),
        ),
    ]
