# Generated by Django 4.2.7 on 2026-01-21 12:39

import ai_image.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the image', max_length=200)),
                ('prompt', models.TextField(help_text='Detailed description for image generation')),
                ('negative_prompt', models.TextField(blank=True, help_text='What to avoid in the image', null=True)),
                ('style', models.CharField(choices=[('realistic', 'Realistic'), ('artistic', 'Artistic'), ('anime', 'Anime/Manga'), ('cartoon', 'Cartoon'), ('3d_render', '3D Render'), ('watercolor', 'Watercolor'), ('oil_painting', 'Oil Painting'), ('digital_art', 'Digital Art'), ('pixel_art', 'Pixel Art'), ('sketch', 'Sketch/Drawing'), ('cinematic', 'Cinematic'), ('fantasy', 'Fantasy'), ('minimalist', 'Minimalist'), ('vintage', 'Vintage/Retro'), ('neon', 'Neon/Cyberpunk')], default='realistic', max_length=30)),
                ('size', models.CharField(choices=[('512x512', '512x512'), ('768x768', '768x768'), ('1024x1024', '1024x1024'), ('1024x576', '1024x576 (Landscape)'), ('576x1024', '576x1024 (Portrait)'), ('1920x1080', '1920x1080 (Full HD)'), ('1080x1920', '1080x1920 (Story)')], default='1024x1024', max_length=20)),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('high', 'High Quality'), ('ultra', 'Ultra HD')], default='high', max_length=20)),
                ('logo_position', models.CharField(choices=[('none', 'No Logo'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('top_center', 'Top Center'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('bottom_center', 'Bottom Center'), ('center', 'Center')], default='none', max_length=20)),
                ('logo_size', models.IntegerField(default=10, help_text='Logo size as percentage of image (5-30)')),
                ('logo_opacity', models.IntegerField(default=100, help_text='Logo opacity (10-100)')),
                ('seed', models.IntegerField(blank=True, help_text='Seed for reproducibility', null=True)),
                ('enhance_prompt', models.BooleanField(default=True, help_text='AI-enhance the prompt')),
                ('add_lighting', models.CharField(blank=True, choices=[('', 'Default'), ('natural', 'Natural Light'), ('studio', 'Studio Lighting'), ('dramatic', 'Dramatic'), ('soft', 'Soft/Diffused'), ('golden_hour', 'Golden Hour'), ('neon', 'Neon Lights'), ('backlit', 'Backlit')], max_length=50, null=True)),
                ('camera_angle', models.CharField(blank=True, choices=[('', 'Default'), ('front', 'Front View'), ('side', 'Side View'), ('aerial', "Aerial/Bird's Eye"), ('low_angle', 'Low Angle'), ('high_angle', 'High Angle'), ('closeup', 'Close-up'), ('wide', 'Wide Shot'), ('macro', 'Macro')], max_length=50, null=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to=ai_image.models.generated_image_path)),
                ('generated_image_with_logo', models.ImageField(blank=True, null=True, upload_to=ai_image.models.generated_image_path)),
                ('enhanced_prompt', models.TextField(blank=True, help_text='AI-enhanced prompt used', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Generation',
                'verbose_name_plural': 'Image Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_file', models.ImageField(upload_to=ai_image.models.logo_upload_path)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_gemini_api_key', models.TextField(blank=True, db_column='gemini_api_key', null=True)),
                ('default_style', models.CharField(choices=[('realistic', 'Realistic'), ('artistic', 'Artistic'), ('anime', 'Anime/Manga'), ('cartoon', 'Cartoon'), ('3d_render', '3D Render'), ('watercolor', 'Watercolor'), ('oil_painting', 'Oil Painting'), ('digital_art', 'Digital Art'), ('pixel_art', 'Pixel Art'), ('sketch', 'Sketch/Drawing')], default='realistic', max_length=50)),
                ('default_size', models.CharField(choices=[('512x512', '512x512 (Small)'), ('768x768', '768x768 (Medium)'), ('1024x1024', '1024x1024 (Large)'), ('1024x576', '1024x576 (Landscape)'), ('576x1024', '576x1024 (Portrait)'), ('1920x1080', '1920x1080 (Full HD)')], default='1024x1024', max_length=20)),
                ('total_images_generated', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Image Settings',
                'verbose_name_plural': 'User Image Settings',
            },
        ),
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to=ai_image.models.generated_image_path)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_image.imagegeneration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all users')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('social_media', 'Social Media'), ('marketing', 'Marketing'), ('product', 'Product'), ('portrait', 'Portrait'), ('landscape', 'Landscape'), ('abstract', 'Abstract'), ('logo_design', 'Logo Design'), ('banner', 'Banner/Header'), ('illustration', 'Illustration'), ('other', 'Other')], max_length=30)),
                ('prompt_template', models.TextField(help_text='Use {subject}, {style}, {color} as placeholders')),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('recommended_style', models.CharField(choices=[('realistic', 'Realistic'), ('artistic', 'Artistic'), ('anime', 'Anime/Manga'), ('cartoon', 'Cartoon'), ('3d_render', '3D Render'), ('watercolor', 'Watercolor'), ('oil_painting', 'Oil Painting'), ('digital_art', 'Digital Art'), ('pixel_art', 'Pixel Art'), ('sketch', 'Sketch/Drawing'), ('cinematic', 'Cinematic'), ('fantasy', 'Fantasy'), ('minimalist', 'Minimalist'), ('vintage', 'Vintage/Retro'), ('neon', 'Neon/Cyberpunk')], default='realistic', max_length=30)),
                ('recommended_size', models.CharField(choices=[('512x512', '512x512'), ('768x768', '768x768'), ('1024x1024', '1024x1024'), ('1024x576', '1024x576 (Landscape)'), ('576x1024', '576x1024 (Portrait)'), ('1920x1080', '1920x1080 (Full HD)'), ('1080x1920', '1080x1920 (Story)')], default='1024x1024', max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='prompt_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_image.userlogo'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL),
        ),
    ]
