# Generated by Django 4.2.7 on 2026-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0004_imagegeneration_brand_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='brand_style_anchor',
            field=models.TextField(blank=True, help_text='Reusable brand visual DNA summary', null=True),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='failure_codes',
            field=models.JSONField(blank=True, help_text="Failure taxonomy codes e.g. ['C1','L2']", null=True),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='prompt_engineering_used',
            field=models.BooleanField(default=False, help_text='Whether 9-layer prompt engineering was applied'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='reprompt_attempt',
            field=models.IntegerField(default=0, help_text='Re-prompt attempt number (max 3)'),
        ),
    ]
