# Generated by Django 6.0.3 on 2026-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0006_add_copy_overlay_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagesettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-image-1.5', 'GPT Image 1.5 (Best)'), ('dall-e-3', 'DALL-E 3'), ('dall-e-2', 'DALL-E 2 (Faster)')], default='gpt-image-1.5', max_length=50),
        ),
    ]
