# Generated by Django 4.2.7 on 2026-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_contentidea_media_preference_trendingcache_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_dna_source',
            field=models.CharField(blank=True, choices=[('website', 'Website Crawl'), ('pdf', 'Brand Guide PDF'), ('manual', 'Manual'), ('structured', 'Structured Input')], max_length=20),
        ),
        migrations.AlterField(
            model_name='branddnahistory',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('manual', 'Manual'), ('structured', 'Structured Input')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='branddnahistory',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
