# Generated by Django 4.2.7 on 2026-02-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brand_brand_dna_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besttimesuggestion',
            name='source',
            field=models.CharField(choices=[('own_data', 'Own Analytics Data'), ('industry_default', 'Industry Default'), ('competitor_analysis', 'Competitor Analysis')], default='industry_default', max_length=20),
        ),
        migrations.AlterField(
            model_name='trendingcache',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('google', 'Google Trends'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrendFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=500)),
                ('is_accepted', models.BooleanField()),
                ('source_trending_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_feedback', to='brands.brand')),
            ],
            options={
                'db_table': 'trend_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'is_accepted'], name='trend_feedb_brand_i_53582c_idx')],
                'unique_together': {('brand', 'topic_text')},
            },
        ),
    ]
