# Generated by Django 6.0.3 on 2026-03-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_alter_besttimesuggestion_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('brand_dna', 'Brand DNA'), ('competitors', 'Competitor Analysis'), ('pillars', 'Content Pillars'), ('trending', 'Trending Topics'), ('ideas', 'Content Ideas'), ('suggest_competitors', 'Competitor Suggestions')], max_length=30)),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to='brands.brand')),
            ],
            options={
                'db_table': 'prompt_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'feature', '-created_at'], name='prompt_hist_brand_i_436562_idx')],
            },
        ),
    ]
