# Generated by Django 4.2.7 on 2026-03-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_caption', '0002_add_userapisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapisettings',
            name='default_gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AddField(
            model_name='userapisettings',
            name='default_llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', max_length=20),
        ),
    ]
