# Generated by Django 4.2.7 on 2026-03-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_caption', '0003_userapisettings_default_gemini_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapisettings',
            name='default_claude_model',
            field=models.CharField(choices=[('claude-sonnet-4-20250514', 'Claude Sonnet 4 (Recommended)'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 (Faster & Cheaper)')], default='claude-sonnet-4-20250514', max_length=80),
        ),
        migrations.AlterField(
            model_name='userapisettings',
            name='default_llm_provider',
            field=models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='claude', max_length=20),
        ),
    ]
