# Generated by Django 4.2.7 on 2026-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogeneration',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Product photo used as reference for video generation', null=True, upload_to='video_references/%Y/%m/'),
        ),
    ]
